<?php
declare(strict_types=1);
$roots=['Pam\\Native\\Realtime\\'=>dirname(__DIR__).'/src/','Pam\\Native\\Testing\\'=>dirname(__DIR__,2).'/pam-native-testing/src/','Pam\\Native\\'=>dirname(__DIR__,2).'/../pam-native/packages/native/src/'];spl_autoload_register(static function(string$c)use($roots):void{foreach($roots as$p=>$r)if(str_starts_with($c,$p)){$f=$r.str_replace('\\','/',substr($c,strlen($p))).'.php';if(is_file($f))require$f;return;}});
use Pam\Native\Internal\Wire;use Pam\Native\Realtime\Realtime;use Pam\Native\Realtime\RealtimeEventKind;use Pam\Native\Testing\NativeTestHarness;
$tests=[];$test=static function(string$n,Closure$f)use(&$tests):void{$tests[$n]=$f;};
$test('opens secure typed connection',static function():void{$fake=NativeTestHarness::install();$fake->succeed('realtime','connect',['identifier'=>'socket-1']);$id=null;(new Realtime())->connect('wss://realtime.example.test/app',['Authorization'=>'Bearer token'],['pam.v1'],static function($v)use(&$id):void{$id=$v;});$payload=Wire::decodeMap($fake->lastCall()->payload);if($id!=='socket-1'||$payload['protocols']!=='pam.v1'||$payload['maxMessageBytes']!==1048576)throw new RuntimeException('connect mismatch');NativeTestHarness::uninstall();});
$test('maps polled binary event',static function():void{$fake=NativeTestHarness::install();$fake->succeed('realtime','poll',['kind'=>3,'payload'=>base64_encode("\x00\x01"),'code'=>0]);$event=null;(new Realtime())->poll('socket-1',static function($v)use(&$event):void{$event=$v;},0);if($event?->kind!==RealtimeEventKind::Binary||$event->binary()!=="\x00\x01")throw new RuntimeException('event mismatch');NativeTestHarness::uninstall();});
$test('rejects plaintext websocket endpoints',static function():void{try{(new Realtime())->connect('ws://example.test',[],[],static function():void{});throw new RuntimeException('ws accepted');}catch(InvalidArgumentException){}});
$failed=0;foreach($tests as$n=>$f){try{$f();fwrite(STDOUT,"PASS $n\n");}catch(Throwable$e){$failed++;fwrite(STDERR,"FAIL $n: {$e->getMessage()}\n");}}fwrite(STDOUT,count($tests)." tests, $failed failures\n");exit($failed?1:0);
